backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "videos"
    label: "旅遊影片清單"
    files:
      - file: "data/videos.json"
        label: "旅遊影片"
        name: "videos"
        format: "json"
        fields:
          - label: "影片清單"
            name: "videos"
            widget: "list"
            fields:
              - { label: "標題", name: "title", widget: "string" }
              - { label: "說明", name: "description", widget: "text" }
              - { label: "影片網址", name: "url", widget: "string" }
              - { label: "分類", name: "category", widget: "string" }
